services:
  solution:
    build:
      context: .
      args:
        IMAGE: ubuntu:20.04
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    privileged: true
    command: python3.10 /solution/main.py

    volumes:
      - ./solution/:/solution
      - /dev/:/dev/

    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY
      - TASK_ID=24
      - SERVER_ADDRESS=10.128.73.40
      - SERVER_PORT=8000
